menu:
  Home: /
  Archives: /archives
  About: /about/
#If you dont want it, just comment it out
twitter: https://twitter.com/LunaTsukinashi
github: https://github.com/Xi80
email: mailto:tampopo@osashimi.pro

#Put into /source
avator: avator.jpg
